/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.nio.file.Path;
import java.util.Arrays;

public class App {

    public static void main(String[] args) throws IOException {

            Bitmap brokenDown = new Bitmap(args[0]);

            switch (args[2].toLowerCase()) {
                case ("greyscale") : brokenDown.greyScale();
                    break;
                case ("negative") : brokenDown.negative();
                    break;
                case ("rotatecolors") : brokenDown.rotateColors();
            }

            brokenDown.writeBitmap(args[1]);

        }
}
